IMPORTING PANDAS LIBRARY

In [4]:
import pandas as pd

LOADING THE CSV FILE

In [6]:
df=pd.read_csv('/student_data_100_preprocess.csv')

DISPLAYING THE FIRST FIVE AND LAST FIVE ROWS

In [7]:
df.head()

   Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
0    Male   NaN            1.0        65.0           Graduate         95.0
1  Female  21.0            1.0        80.0           Graduate         70.0
2    Male   NaN            3.0        60.0       Postgraduate         60.0
3    Male  21.0            2.0        60.0        High School         80.0
4    Male  20.0            5.0        80.0           Graduate          NaN

In [8]:
df.tail()

    Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
95  Female  18.0            6.0         NaN       Postgraduate         65.0
96  Female  20.0            6.0        95.0        High School          NaN
97  Female  20.0            3.0        80.0                NaN         75.0
98  Female  18.0            6.0        60.0                NaN         50.0
99    Male  19.0            8.0        90.0                NaN         90.0

SHAPE OF DATASET

In [11]:
print(df.shape)

(100, 6)

DATA TYPES

In [12]:
print(df.dtypes)

Gender                 object
Age                   float64
Hours_Studied         float64
Attendance            float64
Parental_Education     object
Final_Score           float64
dtype: object

PRINTING COLUMN NAMES

In [15]:
print(df.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Gender', 'Age', 'Hours_Studied', 'Attendance', 'Parental_Education',
       'Final_Score'],
      dtype='object')>

IDENTIFYING NUMERICAL AND CATEGORICAL COLUMNS

In [16]:
numerical_columns = df.select_dtypes(include=['number']).columns.tolist()
categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()

STATISTICAL SUMMARY

In [17]:
df.describe()

             Age  Hours_Studied  Attendance  Final_Score
count  91.000000      90.000000   92.000000    93.000000
mean   19.417582       4.366667   76.684783    74.247312
std     1.174412       2.348559   11.843234    14.632198
min    18.000000       1.000000   60.000000    50.000000
25%    18.000000       3.000000   65.000000    60.000000
50%    19.000000       4.000000   77.500000    75.000000
75%    21.000000       6.000000   85.000000    90.000000
max    21.000000       8.000000   95.000000    95.000000

MISSING VALUES

In [18]:
missing_values = df.isnull().sum()

In [19]:
print(missing_values)

Gender                 0
Age                    9
Hours_Studied         10
Attendance             8
Parental_Education    13
Final_Score            7
dtype: int64

In [20]:
columns_with_missing = missing_values[missing_values > 0]
print(columns_with_missing)

Age                    9
Hours_Studied         10
Attendance             8
Parental_Education    13
Final_Score            7
dtype: int64

In [21]:
print(df.dtypes)

Gender                 object
Age                   float64
Hours_Studied         float64
Attendance            float64
Parental_Education     object
Final_Score           float64
dtype: object

In [25]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [26]:
missing_values_after_age_imputation = df.isnull().sum()
print('Missing values after Age imputation:')
print(missing_values_after_age_imputation)

Missing values after Age imputation:
Gender                 0
Age                    0
Hours_Studied         10
Attendance             8
Parental_Education    13
Final_Score            7
dtype: int64

In [29]:
df['Parental_Education'] = df['Parental_Education'].fillna(df['Parental_Education'].mode()[0])

IDENTIFYING WHICH NEEDS TO BE FILLED BY MEAN AND MODE

In [33]:
numerical_cols = df.select_dtypes(include=['number']).columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

print("Columns for Mean Filling")
for col in numerical_cols:
    if df[col].isnull().sum() > 0:
        print(col)

print("\nColumns for Mode Filling")
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        print(col)

Columns for Mean Filling
Hours_Studied
Attendance
Final_Score

Columns for Mode Filling

In [34]:
num_cols = ['Age', 'Hours_Studied', 'Attendance', 'Final_Score']

for col in num_cols:
    mean_value = df[col].mean()
    df[col] = df[col].fillna(mean_value)

In [35]:
cat_cols = ['Gender', 'Parental_Education']

for col in cat_cols:
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

In [36]:
print(df.isnull().sum().sum())

0

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Gender              100 non-null    object
 1   Age                 100 non-null    float64
 2   Hours_Studied       100 non-null    float64
 3   Attendance          100 non-null    float64
 4   Parental_Education  100 non-null    object
 5   Final_Score         100 non-null    float64
dtypes: float64(4), object(2)
memory usage: 4.8+ KB

In [39]:
df.describe()

              Age  Hours_Studied  Attendance  Final_Score
count  100.000000     100.000000  100.000000   100.000000
mean    19.417582       4.366667   76.684783    74.247312
std      1.119758       2.226788   11.354641    14.105415
min     18.000000       1.000000   60.000000    50.000000
25%     18.000000       3.000000   65.000000    65.000000
50%     19.000000       4.000000   76.684783    75.000000
75%     20.250000       6.000000   85.000000    85.000000
max     21.000000       8.000000   95.000000    95.000000

In [40]:
from sklearn.preprocessing import LabelEncoder

IMPORTING FOR ENCDING

In [41]:
le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])

LABEL ENCODING FOR GENDER

In [42]:
parent_edu_encoded = pd.get_dummies(
    df['Parental_Education'],
    prefix='PE'
)

ONE HOT ENCODING PERFORMED ON PARENTAL EDUCATION

In [43]:
df = df.drop('Parental_Education', axis=1)

In [ ]:
REMOVING THE ORIGINAL CATEGORICAL COLUMN

In [44]:
df = pd.concat([df, parent_edu_encoded], axis=1)

ADDING ENCODED COLUMN TO DATASET

In [45]:
print(df.dtypes)

Gender               int64
Age                float64
Hours_Studied      float64
Attendance         float64
Final_Score        float64
PE_Graduate           bool
PE_High School        bool
PE_Postgraduate       bool
dtype: object

FINALLY CONFIRMING IF DATA TYPES ARE MACHINE READABLE OR NOT

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           100 non-null    int64
 1   Age              100 non-null    float64
 2   Hours_Studied    100 non-null    float64
 3   Attendance       100 non-null    float64
 4   Final_Score      100 non-null    float64
 5   PE_Graduate      100 non-null    bool
 6   PE_High School   100 non-null    bool
 7   PE_Postgraduate  100 non-null    bool
dtypes: bool(3), float64(4), int64(1)
memory usage: 4.3 KB

In [ ]:
PREARING THE DATASET FOR MODEL TRAINING

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X = df.drop('Final_Score', axis=1)
y = df['Final_Score']

SEPARATING FEATURES AND TARGET

In [49]:
X_train, X_test, y_train, y_test = train_test_split( X,y, test_size=0.20,random_state=42    )

SPLITTING DATASET 20% FOR TESTING AND REMAINING FOR TRAINING ALSO I HAVE INCLUDED RANDOM STATE

In [50]:
print("Training Samples:", len(X_train))
print("Testing Samples :", len(X_test))

Training Samples: 80
Testing Samples : 20

In [ ]:
VERIFYING THE SPLIT